=== modoumanta/cabinetInfirmier/Data/xsd/cabinet.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:ca="http://www.univ-grenoble-alpes.fr/l3miage/medical/cabinet"
        targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/medical/cabinet"
        elementFormDefault="qualified"
>
    <!--******************************** Type Cabinet *******************************-->
    
    <element name="cabinet" type="ca:Cabinet">
        <keyref name="idIntervenant" refer="ca:idInfirmier">
            <selector xpath="ca:patients/ca:patient/ca:visite/ca:intervenant"/>
            <field xpath="@id"/>
        </keyref>
        <keyref name="idNgap" refer="ca:idActe">
            <selector xpath="ca:patients/ca:patient/ca:visite"/>
            <field xpath="@acte"/>
        </keyref>
        
        <keyref name="idVisite" refer="ca:visite">
            <selector xpath="ca:patients/ca:patient/ca:visite"/>
            <field xpath="@acte"/>
            <field xpath="ca:date"/>
            <field xpath="ca:intervenant"/>
        </keyref>

    </element>
    
    <!--************************** Declaration de type Cabinet **********************-->
    
    <complexType name="Cabinet">
        <sequence>
            <!-- definition de Adresse -->
            <element name="adresse" type="ca:Adresse"/>
            
            <!-- definition de Infirmiers -->
            <element name="infirmiers" type="ca:Infirmiers">
                <unique name="idInfirmier">
                    <selector xpath="ca:infirmier"/>
                    <field xpath="@id"/>
                </unique>
            </element>
            
            <!-- definition de Patient -->
            
            <element name="patients" type="ca:Patients">
                <unique name="idPatient">
                    <selector xpath="ca:patient"/>
                    <field xpath="ca:numeroSecu"/>
                </unique>
            </element>
            
            <!-- definition de acte -->
            <element name="acte" type="ca:Ngap"/>
        </sequence>
        <attribute name="nom" type="string"/>
    </complexType>
    
    <!--************************** Declaration de type Infirmiers **********************-->
    
    <complexType name="Infirmiers">
        <sequence>
            <element name="infirmier" type="ca:Infirmier" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!--************************** Declaration de type Infirmier **********************-->
    
    <complexType name="Infirmier">
        <sequence>
            <element name="nom" type="ca:NomPrenom"/>
            <element name="prenom" type="ca:NomPrenom"/>
            <element name="photo" type="string"/>
        </sequence>
        <attribute name="id" type="int"/>
    </complexType>
    <simpleType name="NomPrenom">
        <restriction base="string">
            <minLength value="3"/>
            <maxLength value="30"/>
        </restriction>
    </simpleType>
    
    
    <!--************************** Declaration de type Patient **********************-->
    
    <complexType name="Patients">
        <sequence>
            <element name="patient" type="ca:Patient" minOccurs="1" maxOccurs="unbounded">
                <unique name="idVisitePatient" >
                    <selector xpath="ca:visite"/>
                    <field xpath="@acte"/>
                    <field xpath="ca:date"/>
                </unique>
            </element>
           
        </sequence>
    </complexType>
    
    <complexType name="Patient">
        <sequence>
            <element name="nom" type="ca:NomPrenom"/>
            <element name="prenom" type="ca:NomPrenom"/>
            <element name="sexe" type="ca:Sexe"/>
            <element name="numeroSecu" type="ca:NumeroSecu"/>
            <element name="naissance" type="date"/>
            <element name="adresse" type="ca:Adresse"/>
            <element name="visite" type="ca:Visite" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    
    <!--************************** Declaration de type Sexe ************************-->
    
    <simpleType name="Sexe">
        <restriction base="string">
            <enumeration value="F"/>
            <enumeration value="M"/>
        </restriction>
    </simpleType>
    
    <!--************************** Declaration de type NumeroSecu ***********************-->
    <!--<simpleType name="NumeroSecu">
        <restriction base="string">
            <pattern value="[MF][0-9]{2}[0-9]{2}[0-9]{2}[0-9]{3}[0-9]{4}[0-9]{2}"/>
        </restriction>
    </simpleType>-->
    
    <simpleType name="NumeroSecu">
        <restriction base="string">
            <pattern value="[1-2]{1}[0-9]{2}[0-9]{2}[0-9]{2}[0-9]{3}[0-9]{3}[0-9]{2}"/>
        </restriction>
    </simpleType>
    
    <!--************************** Declaration de type Adresse ***********************-->
    
    <complexType name="Adresse">
        <sequence>
            <element name="numero" type="int"/>
            <element name="rue" type="ca:Rue"/>
            <element name="codePostal" type="ca:CodePostal"/>
            <element name="ville" type="ca:Ville"/>
            <element name="etage" type="int"/>
        </sequence>
    </complexType>
    <simpleType name="Rue">
        <restriction base="string">
            <minLength value="5"/>
            <maxLength value="50"/>
        </restriction>
    </simpleType>
    
    <simpleType name="Ville">
        <restriction base="string">
            <minLength value="3"/>
            <maxLength value="30"/>
        </restriction>
    </simpleType>
    
    
    <!--************************** Declaration de type CodePostal ***********************-->
    
    <simpleType name="CodePostal">
        <restriction base="string">
            <pattern value="[0-9]{5}"/>
        </restriction>
    </simpleType>
    
    <!--************************** Declaration de type Visite ***********************-->
    
    <complexType name="Visite">
        <sequence>
            <element name="date" type="date"/>
            <element name="intervenant" type="ca:Intervenant"/>
        </sequence>
        <attribute name="acte" type="string"/>
    </complexType>
    
    <complexType name="Intervenant">
        <attribute name="id" type="integer"/>
    </complexType>
    
    <!--************************** Declaration de type Ngap ***********************-->
    
    <complexType name="Ngap">
        <sequence>
            <element name="types" type="ca:Types">
                <unique name="idType">
                    <selector xpath="ca:type"/>
                    <field xpath="@id"/>
                </unique>
            </element>
            <element name="actes" type="ca:Actes">
                <unique name="idActe">
                    <selector xpath="ca:acte"/>
                    <field xpath="@id"/>
                </unique>
            </element>
        </sequence>
    </complexType>
    
    <complexType name="Types">
        <sequence>
            <element name="type" maxOccurs="unbounded" type="ca:Type"/>
        </sequence>
    </complexType>
    
    <complexType name="Type" mixed="true">
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="pi"/> <!-- Prélèvements et injections -->
                    <enumeration value="pc"/> <!-- Pansements courants -->
                    <enumeration value="pl"/> <!-- Pansements lourds et complexes -->
                    <enumeration value="sd"/> <!-- Soins infirmiers à domicile -->
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    
    <complexType name="Actes">
        <sequence>
            <element name="acte" maxOccurs="unbounded" type="ca:Acte" />
        </sequence>
    </complexType>
    
    <complexType name="Acte" mixed="true">
        <attribute name="id" type="string" use="required"/>
        <attribute name="type" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="pi"/>
                    <enumeration value="pc"/>
                    <enumeration value="pl"/>
                    <enumeration value="sd"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="clé" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="AMI"/>
                    <enumeration value="AIS"/>
                    <enumeration value="DI"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="coef" use="required">
            <simpleType>
                <restriction base="decimal">
                    <enumeration value="1"/>
                    <enumeration value="1.5"/>
                    <enumeration value="2"/>
                    <enumeration value="2.25"/>
                    <enumeration value="2.5"/>
                    <enumeration value="3"/>
                    <enumeration value="4.1"/>
                    <enumeration value="5"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

</schema>

=== modoumanta/cabinetInfirmier/Data/xml/cabinet.xml
<?xml version="1.0" encoding="utf-8"?>

<cabinet nom="Soins a Grenoble"
         xmlns="http://www.univ-grenoble-alpes.fr/l3miage/medical/cabinet"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/medical/cabinet ../xsd/cabinet.xsd">
    <adresse>
        <numero>2</numero>
        <rue>avenue des jeux olympiques</rue>
        <codePostal>38100</codePostal>
        <ville>Grenonle</ville>
        <etage>2</etage>
    </adresse>

    <infirmiers>
        <infirmier id="001">
            <nom>GUEYE</nom>
            <prenom>Ahmadou </prenom>
            <photo>uhjdh.jpg</photo>
        </infirmier>
        <infirmier id="002">
            <nom>loli</nom>
            <prenom>lola</prenom>
            <photo>fgfhgk.jkhk</photo>
        </infirmier>
    </infirmiers>
    <patients>
        <patient>
            <nom>Elaouad</nom>
            <prenom>Zineb</prenom>
            <sexe>F</sexe>
            <numeroSecu>2123456789012345</numeroSecu>
            <naissance>2023-09-03</naissance>
            <adresse>
                <numero>2</numero>
                <rue>avenue des jeux olympiques</rue>
                <codePostal>38100</codePostal>
                <ville>Grenonle</ville>
                <etage>2</etage>
            </adresse>
            <visite acte="103" >
                <date>2024-09-26</date>
                <intervenant id="002"/>
            </visite>

        </patient>
        <patient>
            <nom>nadjidatie</nom>
            <prenom>houssouny</prenom>
            <sexe>F</sexe>
            <numeroSecu>2990112345678901</numeroSecu>
            <naissance>2023-09-03</naissance>
            <adresse>
                <numero>2</numero>
                <rue>avenue des jeux olympiques</rue>
                <codePostal>38100</codePostal>
                <ville>Grenonle</ville>
                <etage>2</etage>
            </adresse>
            <visite acte="103" >
                <date>2024-09-26</date>
                <intervenant id="002"/>
            </visite>
        </patient>

    </patients>


    <acte>
        <types>
            <type id="pi">prélèvements et injections</type>
            <type id="pc">pansements courants</type>
            <type id="pl">
                pansements lourds et complexes nécessitant des conditions
                d'asepsie rigoureuse
            </type>
            <type id="sd">
                Soins infirmiers à domicile pour un patient, quel que
                soit son âge, en situation de dépendance temporaire ou permanente.
            </type>
        </types>
        <actes>
            <acte id="101" type="pi" clé="AMI" coef="1.5">
                Prélèvement par ponction veineuse directe
            </acte>
            <acte id="102" type="pi" clé="AMI" coef="5">
                Saignée
            </acte>
            <acte id="103" type="pi" clé="AMI" coef="1">
                Prélèvement aseptique cutané ou de sécrétions muqueuses, prélèvement
                de selles ou d'urine pour examens cytologiques, bactériologiques, mycologiques.
            </acte>
            <acte id="104" type="pi" clé="AMI" coef="2">
                Injection intraveineuse directe isolée.
            </acte>
            <acte id="105" type="pi" clé="AMI" coef="1.5">
                Injection intraveineuse directe en série.
            </acte>
            <acte id="106" type="pi" clé="AMI" coef="2">
                Injection intraveineuse directe chez un enfant de moins de 5 ans.
            </acte>
            <acte id="107" type="pi" clé="AMI" coef="1">
                Injection intramusculaire.
            </acte>
            <acte id="108" type="pi" clé="AMI" coef="5">
                Injection d'un sérum d'origine humaine ou animale selon la méthode de
                Besredka, y compris la surveillance.
            </acte>
            <acte id="109" type="pi" clé="AMI" coef="1">
                Injection sous-cutanée.
            </acte>
            <acte id="110" type="pi" clé="AMI" coef="1">
                Injection intradermique.
            </acte>
            <acte id="111" type="pi" clé="AMI" coef="3">
                Injection d'un ou plusieurs allergènes, poursuivant un traitement
                d'hyposensibilisation spécifique, selon le protocole écrit, y compris la
                surveillance, la tenue du dossier de soins, la transmission des informations
                au médecin prescripteur.
            </acte>
            <acte id="112" type="pi" clé="AMI" coef="2.5">
                Injection d'un implant sous-cutané.
            </acte>
            <acte id="113" type="pi" clé="AMI" coef="2">
                Injection en goutte à goutte par voie rectale.
            </acte>

            <acte id="200" type="pc" clé="AMI" coef="2">
                Pansement de stomie
            </acte>
            <acte id="201" type="pc" clé="AMI" coef="2.25">
                Pansement de trachéotomie, y compris l'aspiration et l'éventuel
                changement de canule.
            </acte>
            <acte id="202" type="pc" clé="AMI" coef="2">
                Ablation de fils ou d'agrafes, dix ou moins, y compris le pansement
                éventuel.
            </acte>
            <acte id="203" type="pc" clé="AMI" coef="4.1">
                Ablation de fils ou d'agrafes, plus de dix, y compris le pansement
                éventuel.
            </acte>
            <acte id="204" type="pc" clé="AMI" coef="2">
                Autre pansement.
            </acte>

            <acte id="300" type="pl" clé="AMI" coef="4.1">
                Pansement de brûlure étendue ou de plaie chimique ou thermique étendue,
                sur une surface supérieure à 5% de la surface corporelle.
            </acte>
            <acte id="301" type="pl" clé="AMI" coef="4.1">
                Pansement d'ulcère étendu ou de greffe cutanée, sur une surface
                supérieure à 60 cm².
            </acte>
            <acte id="302" type="pl" clé="AMI" coef="4.1">
                Pansement de fistule digestive.
            </acte>
            <acte id="303" type="pl" clé="AMI" coef="4.1">
                Pansement chirurgical nécessitant un méchage ou une irrigation.
            </acte>

            <acte id="401" type="sd" clé="DI" coef="1.5">
                Élaboration de la démarche de soins infirmiers à domicile, planification
                des soins et rédaction du résumé de la démarche de soins infirmiers.
            </acte>
            <acte id="402" type="sd" clé="AIS" coef="3">
                Mise en œuvre d'un programme d'aide personnalisée.
            </acte>
            <acte id="403" type="sd" clé="AIS" coef="4.1">
                Séance hebdomadaire de surveillance clinique infirmière et de prévention
                par séance d'une demi-heure.
            </acte>
        </actes>
    </acte>
</cabinet>
